name: mobile_threat_defense
description: Mobile Threat Defense App.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  device_info_plus: ^9.1.1
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  flutter_bloc: ^8.1.3
  get_it: ^7.6.7
  crypto: ^3.0.3
  permission_handler: ^11.2.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
